@startuml
left to right direction
skinparam shadowing false

class User {
  password
  email
  is_driver
}

class Trip {
  origin
  destination
  is_in_progress
  passenger_id
  driver_id
}

class Invoice {
  user_id
  trip_id
  amount
}

class Payment {
  invoice_id
  amount
  stripe_charge_id
}

class Vehicle {
  user_id
}

Trip --> User
Vehicle --> User
Invoice --> User
Invoice --> Trip
Payment --> Invoice

@enduml
