@startuml
skinparam shadowing false

class User {
  password
  email
  is_driver
}

class Trip {
  origin
  destination
  is_in_progress
}

class Payment {
  user_id
  trip_id
  amount
  stripe_charge_id
}

User --> Trip
Trip --> User
Trip --> Payment

@enduml
