@startuml
skinparam shadowing false

class User {
  password
  email
  is_driver
  service_tier_id
}

class Trip {
  origin
  destination
  is_in_progress
  service_tier_id
  passenger_id
  driver_id
  vehicle_id
}

class Payment {
  user_id
  trip_id
  amount
  stripe_charge_id
}

class Vehicle {
  user_id
  vehicle_type_id
}

class ServiceTier {
  vehicle_type_id
  rate
}

class VehicleType {
}


User --> Trip
Trip --> User
Trip --> Payment
Trip --> ServiceTier
Trip --> Vehicle
ServiceTier --> VehicleType
Vehicle --> VehicleType
Vehicle --> User
User --> ServiceTier

@enduml
