@startuml
skinparam shadowing false

class User {
  password
  email
  is_driver
}

class Trip {
  origin
  destination
  is_in_progress
  trip_service_tier_id
}

class Payment {
  user_id
  trip_id
  amount
  stripe_charge_id
}

class TripServiceTier {
  vehicle_name
  price
}

User --> Trip
Trip --> User
Trip --> Payment
Trip --> TripServiceTier

@enduml
