@startuml
left to right direction
skinparam shadowing false

class User {
  password
  email
  is_driver
  service_tier_id
}

class Trip {
  origin
  destination
  is_in_progress
  service_tier_id
  passenger_id
  driver_id
  vehicle_id
}

class Invoice {
  user_id
  trip_id
  amount
}

class Payment {
  invoice_id
  amount
  stripe_charge_id
}

class ServiceTier {
  vehicle_type_id
  rate
}

class Vehicle {
  user_id
  vehicle_type_id
}

class VehicleType {
  name
}


Trip --> User
Trip --> ServiceTier
Trip --> Vehicle
Vehicle --> User
Invoice --> User
Invoice --> Trip
Payment --> Invoice
ServiceTier --> VehicleType
Vehicle --> VehicleType
User --> ServiceTier

@enduml
