@startuml
skinparam shadowing false

class User {
  password
  email
  is_driver
  service_tier_id
}

class Trip {
  origin
  destination
  is_in_progress
  service_tier_id
  passenger_id
  driver_id
  vehicle_id
  trip_pool_id
}

class Vehicle {
  user_id
  gigawatt_output_rating
  service_tier_id
}

class Payment {
  user_id
  trip_id
  order_id
  amount
  stripe_charge_id
}

class TripServiceTier {
  rate
  is_eligible_for_trip_pooling
}

class Order {
  user_id
}

class TripPool {
}


class OrderMenuItem {
  order_id
  menu_item_id
}


class Restaurant {
  begin_date
  end_date
}

class Menu {
  restaurant_id
}

class MenuItem {
  store_id
  name
  cost
  inventory_count
}

class InflationAdjustment {
  date
  rate_change
}

User --> Order
OrderMenuItem --> Order
OrderMenuItem --> MenuItem
Restaurant --> Menu
Menu --> MenuItem

User --> Trip
Trip --> User
Trip --> Payment
Trip --> TripServiceTier
TripServiceTier --> VehicleType
Vehicle --> VehicleType
User --> Vehicle
TripPool --> Trip

@enduml
