@startuml
skinparam shadowing false

class User {
  password
  email
  is_driver
}

class Trip {
  origin
  destination
  is_in_progress
  trip_service_tier_id
  trip_pool_id
}

class TripPool {
}

class TripRouterService {
}

class BillingService {
}

class Payment {
  user_id
  trip_id
  order_id
  amount
  stripe_charge_id
}

class TripServiceTier {
  vehicle_name
  price
  is_eligible_for_trip_pooling
}

class Order {
  user_id
}

User --> Order

class OrderMenuItem {
  order_id
  menu_item_id
}


class Restaurant {
  begin_date
  end_date
}

class Menu {
  restaurant_id
}

class MenuItem {
  store_id
  name
  cost
  inventory_count
}

class InflationAdjustment {
  date
  rate_change
}

OrderMenuItem --> Order
OrderMenuItem --> MenuItem
Restaurant --> Menu
Menu --> MenuItem

User --> Trip
Trip --> User
Trip --> Payment
Trip --> TripServiceTier
TripPool --> Trip

@enduml
